# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mod Properties
mod_id=insomnia
mod_name=Insomnia
mod_license=MIT
mod_version=1.2.1
mod_group_id=github.jodevnull
mod_authors=jo-devnull
mod_description=Custom tweaks

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

# NeoForge
neo_version=21.1.227
neo_version_range=[21,)
loader_version_range=[4,)
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

# Dependencies
irons_spellbooks=1.21.1-3.15.6

modrinth.emi=1.1.22+1.21.1+neoforge
modrinth.in-control=1.21-10.2.6
modrinth.curios=9.5.1+1.21.1
modrinth.irons-lib=1.21.1-1.0.2
modrinth.geckolib=gFmrC8Ru
modrinth.playeranimator=2.0.4+1.21.1-forge
modrinth.enhanced-celestials=6.0.2.5-neoforge
modrinth.data-anchor=2.0.0.14-neoforge
modrinth.corgilib=1.21.1-5.0.0.9-NeoForge

modrinth.create=6.0.10+mc1.21.1 @runtimeOnly
modrinth.create-metallurgy=1.0.2-1.21.1 @runtimeOnly
modrinth.jei=YAcQ6elZ @runtimeOnly

curseforge.architectury-api=419699:5786327
curseforge.ftb-library-forge=404465:7746959
curseforge.ftb-teams-forge=404468:7878281
curseforge.ftb-quests-forge=289412:7878289

