org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.4.13
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1
parchment=2023.09.03

mod_id=insomnia
mod_name=Insomnia
mod_license=All Rights Reserved
mod_version=0.5.0-BETA
mod_group_id=com.github.dylanxyz
mod_authors=dylanxyz
mod_description=Tweaks for my custom modpack called Insomnia

# Dependencies

irons_spells        = 1.20.1-3.15.6
ironslib            = curse.maven:irons-lib-1492763:7907335
geckolib            = curse.maven:geckolib-388172:7553267
curios              = curse.maven:curios-309927:6418456
playeranimator      = curse.maven:playeranimator-658587:4587214

emi                 = maven.modrinth:emi:1.1.22+1.20.1+forge
incontrol           = maven.modrinth:in-control:1.20-9.4.6
fromtheshadows      = curse.maven:from-the-shadow-reborn-986907:5967610
framework           = curse.maven:framework-549225:6531428
migamigos           = curse.maven:migamigos-1188039:6129596
enhancedcelestials  = maven.modrinth:enhanced-celestials:1.20.1-5.0.3.1-forge
dataanchor          = maven.modrinth:data-anchor:1.0.0.19-forge
corgilib            = maven.modrinth:corgilib:1.20.1-4.0.3.4-forge
embeddium           = maven.modrinth:embeddium:0.3.31+mc1.20.1
spark               = maven.modrinth:spark:1.10.53-forge

ftb_quests          = curse.maven:ftb-quests-forge-289412:7909594
ftb_teams           = curse.maven:ftb-teams-forge-404468:7499810
ftb_library         = curse.maven:ftb-library-forge-404465:7296748
architectury        = curse.maven:architectury-api-419699:5137938