org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.3.12
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1
parchment=2023.09.03

mod_id=insomnia
mod_name=Insomnia
mod_license=All Rights Reserved
mod_version=0.4.1-BETA
mod_group_id=com.github.dylanxyz
mod_authors=dylanxyz
mod_description=Tweaks for my custom modpack called Insomnia

# Dependencies

figura             = maven.modrinth:figura:4HqSmvZ6
curios             = curse.maven:curios-309927:6418456
emi                = maven.modrinth:emi:1.1.22+1.20.1+forge
incontrol          = maven.modrinth:in-control:1.20-9.4.6
geckolib           = maven.modrinth:geckolib:HVdLnQMI
fromtheshadows     = curse.maven:from-the-shadow-reborn-986907:5967610
framework          = curse.maven:framework-549225:6531428
migamigos          = curse.maven:migamigos-1188039:6129596
enhancedcelestials = maven.modrinth:enhanced-celestials:1.20.1-5.0.3.1-forge
dataanchor         = maven.modrinth:data-anchor:1.0.0.19-forge
corgilib           = maven.modrinth:corgilib:1.20.1-4.0.3.4-forge
embeddium          = maven.modrinth:embeddium:0.3.31+mc1.20.1
spark              = maven.modrinth:spark:1.10.53-forge
class_enhancement  = curse.maven:class-enhancement-1460324:7953461

ironsspells_version=1.20.1-3.4.0.9
caelus             = curse.maven:caelus-308989:5281700
playeranimator     = curse.maven:playeranimator-658587:4587214
